# Generated by Django 5.0.6 on 2024-07-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_video_video_1080p_path_video_video_720p_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='video/thumbs/'),
        ),
    ]
