# Generated by Django 5.0.6 on 2024-07-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_video_video_1080p_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_1080p_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_480p_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
