# Generated by Django 5.0.6 on 2024-07-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_video_video_1080p_path_video_video_480p_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
